name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-
      - uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL
          path: build/WebGL
